TEMPLATE = app
TARGET = a1
CONFIG += qt
QT = core gui opengl #  qt libraries to use
LIBS += -lGLU #is not pulled in by default

HEADERS += *.h
SOURCES += *.cpp
FORMS += MainWindow.ui

QMAKE_CXXFLAGS += -std=c++0x -Wall -Werror
DESTDIR = bin/ # where executable will be placed
MOC_DIR = .build/ # where moc_* files generated by qt will go 
# where intermediate objects generated by compiler, *.o files, will go
OBJECTS_DIR = .build/ 

